spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projectsdb
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PosgreSQLInnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "https.tobias.jara.404@gmail.com"
    password: "Tobias@1004"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enabled: false

stripe:
  apiKey: sk_test_51OltaMAk00cbhskWbLIJPPaOFdhDV73cfdU2UE9Im37jBEusRghuDL0SUertCiGpEqksabX3wKiAopTW1vLf5n9J00Apwvk1Hz